# Generated by Django 5.2.5 on 2026-06-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MESSAGE', 'Message'), ('MEETING', 'Meeting'), ('MENTION', 'Mention'), ('TEAM', 'Team'), ('CHANNEL', 'Channel'), ('SYSTEM', 'System')], max_length=20),
        ),
    ]
