# Generated by Django 5.2.5 on 2026-06-24 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_reaction_unique_reaction_per_user_message'),
        ('teams', '0004_team_team_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['channel', 'created_at'], name='chat_messag_channel_4b0a96_idx'),
        ),
    ]
