# Generated by Django 5.2.5 on 2026-07-08 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_add_is_system_to_message'),
        ('teams', '0006_organizationmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='channelreadreceipt',
            index=models.Index(fields=['user', 'channel'], name='chat_channe_user_id_575063_idx'),
        ),
        migrations.AddIndex(
            model_name='channelreadreceipt',
            index=models.Index(fields=['last_read_message'], name='chat_channe_last_re_2b69e1_idx'),
        ),
    ]
