# Generated by Django 5.2.5 on 2026-07-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_channelreadreceipt_chat_channe_user_id_575063_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="client_uuid",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
