# Generated by Django 5.2.5 on 2026-07-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0003_meetingparticipant_unique_meeting_participant"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meetingparticipant",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
